- name: check that contrib and non-free repos are enabled
  apt_repository:
    repo: "deb http://deb.debian.org/debian {{ ansible_distribution_release }} main contrib non-free non-free-firmware"
    state: present

- name: update apt cache
  apt:
    update_cache: yes

- name: upgrade system
  apt:
    upgrade: dist

- name: check foreign architecture
  command: dpkg --print-foreign-architectures
  register: foreign_arch
  changed_when: false

- name: enable i386 architecture
  command: dpkg --add-architecture i386
  when: "'i386' not in foreign_arch.stdout"

- name: install Steam
  apt:
    name: steam-installer
    state: present

- name: download Discord
  get_url:
    url: "{{ discord_url }}"
    dest: "{{ discord_deb_path }}"

- name: install Discord
  apt:
    deb: "{{ discord_deb_path }}"

- name: install NVIDIA drivers
  apt:
    name: nvidia-driver
    state: present
